import type { Metadata } from 'next';
import { reportStore } from '@/lib/store';

type Props = {
  params: Promise<{ id: string }>;
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params;
  const report = reportStore.get(id);

  if (!report) {
    return {
      title: 'Report Not Found — ScopyAI',
      description: 'This intelligence report could not be found.',
    };
  }

  const score = report.debate?.compositeScore ?? '---';
  const verdict = report.debate?.finalVerdict ?? 'Intelligence report generated by ScopyAI.';

  return {
    title: `ScopyAI Report: ${report.niche}`,
    description: `Composite Score: ${score}/100. ${verdict.slice(0, 150)}`,
    openGraph: {
      title: `ScopyAI Intelligence Report: ${report.niche}`,
      description: `${report.persona} archetype · ${report.sources.length} sources · Score: ${score}/100`,
      type: 'article',
      siteName: 'ScopyAI — AI Market Intelligence Engine',
      locale: 'en_US',
    },
    twitter: {
      card: 'summary_large_image',
      title: `ScopyAI: ${report.niche}`,
      description: `Composite Score: ${score}/100 · ${report.sources.length} intelligence signals`,
    },
    robots: {
      index: true,
      follow: true,
    },
  };
}

export default function ReportLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
