import { Navbar } from '@/components/landing/Navbar';
import { Footer } from '@/components/landing/Footer';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'ScopyAI Terms of Service — the rules governing your use of our AI market intelligence platform.',
};

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <div className="max-w-[740px] mx-auto px-7 py-12">
        <div className="mb-10">
          <span className="font-mono text-[10px] text-accent tracking-[0.1em] uppercase">Legal</span>
          <h1 className="text-[28px] font-medium mt-2">Terms of Service</h1>
          <p className="text-[13px] text-muted mt-2">Last updated: March 28, 2026</p>
        </div>

        <div className="prose-dark space-y-8">
          <section>
            <h2 className="text-[18px] font-medium mb-3">1. Acceptance of Terms</h2>
            <p className="text-[14px] text-muted-2 leading-[1.8]">
              By accessing or using ScopyAI (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not use the Service. We reserve the right to update these terms at any time, with notice provided through the Service.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-medium mb-3">2. Description of Service</h2>
            <p className="text-[14px] text-muted-2 leading-[1.8]">
              ScopyAI provides AI-powered market intelligence reports generated through a combination of live web research, large language models, and proprietary analysis algorithms. Reports include market sizing, competitive analysis, risk assessment, and strategic recommendations.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-medium mb-3">3. Account Registration</h2>
            <p className="text-[14px] text-muted-2 leading-[1.8]">
              You must provide accurate and complete information when creating an account. You are responsible for maintaining the security of your account credentials. You must notify us immediately of any unauthorized access to your account.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-medium mb-3">4. Subscriptions & Billing</h2>
            <ul className="list-disc list-inside space-y-2 text-[14px] text-muted-2 leading-[1.8]">
              <li><strong className="text-text">Explorer (Free):</strong> Limited to 1 report. No credit card required.</li>
              <li><strong className="text-text">Pro ($29/mo):</strong> Unlimited reports, all export formats, Niche Duel, Report Chat, and 30-day signal refresh.</li>
              <li><strong className="text-text">Agency ($99/mo):</strong> Includes everything in Pro, plus white-label PDFs, API access, and client workspace management.</li>
            </ul>
            <p className="text-[14px] text-muted-2 leading-[1.8] mt-3">
              Subscriptions are billed monthly through Stripe. You may cancel at any time. Cancellation takes effect at the end of the current billing period. No refunds are provided for partial months.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-medium mb-3">5. AI-Generated Content Disclaimer</h2>
            <p className="text-[14px] text-muted-2 leading-[1.8]">
              Reports generated by ScopyAI are produced by artificial intelligence models and automated web research tools. While we strive for accuracy, <strong className="text-text">all AI-generated content is provided &quot;as is&quot; without warranty of any kind</strong>. ScopyAI does not guarantee the accuracy, completeness, or reliability of any data, scores, or recommendations in generated reports. You should independently verify all critical business decisions.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-medium mb-3">6. Intellectual Property</h2>
            <p className="text-[14px] text-muted-2 leading-[1.8]">
              You retain ownership of the input data you provide (niche descriptions, competitor URLs, etc.). Generated reports are licensed to you for personal and commercial use under your active subscription. The ScopyAI platform, branding, and underlying algorithms remain our intellectual property.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-medium mb-3">7. Prohibited Uses</h2>
            <ul className="list-disc list-inside space-y-2 text-[14px] text-muted-2 leading-[1.8]">
              <li>Using the Service to generate misleading, defamatory, or illegal content.</li>
              <li>Attempting to reverse-engineer, scrape, or extract the underlying AI models or algorithms.</li>
              <li>Automated or bot-driven mass generation of reports to exhaust system resources.</li>
              <li>Reselling generated reports without an active Agency subscription.</li>
              <li>Circumventing rate limits, credit systems, or security measures.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-[18px] font-medium mb-3">8. Limitation of Liability</h2>
            <p className="text-[14px] text-muted-2 leading-[1.8]">
              To the maximum extent permitted by law, ScopyAI shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service, including but not limited to business losses based on AI-generated recommendations.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-medium mb-3">9. Termination</h2>
            <p className="text-[14px] text-muted-2 leading-[1.8]">
              We reserve the right to suspend or terminate your account at any time for violation of these terms. Upon termination, your access to generated reports may be revoked. You may export your data before account closure.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-medium mb-3">10. Contact</h2>
            <p className="text-[14px] text-muted-2 leading-[1.8]">
              For questions about these Terms, contact us at <a href="mailto:legal@scopyai.com" className="text-accent hover:underline">legal@scopyai.com</a>.
            </p>
          </section>
        </div>
      </div>
      <Footer />
    </>
  );
}
