/**
 * Tri-Agent Debate System
 *
 * Three independent AI agents evaluate the same niche + research data:
 *   Builder  → opportunity maximiser (GO / CAUTION)
 *   Cynic    → risk destroyer (KILL / PIVOT / GO)
 *   Operator → execution reality check (EASY / HARD / IMPOSSIBLE)
 *
 * The Debate Resolver weighs all three and produces a conditional verdict.
 */

import { generateStructuredOutput, MODELS } from './client';
import { agentVerdictSchema, debateResultSchema, type DebateResult } from '@/types/report';
import type { ResearchData } from '@/lib/research/orchestrator';

function researchSummary(research: ResearchData): string {
  return [
    '--- MARKET DATA ---',
    research.marketSize.slice(0, 5).join('\n'),
    '--- COMPETITOR DATA ---',
    research.competitors.slice(0, 5).join('\n'),
    '--- PAIN POINT DATA ---',
    research.painPoints.slice(0, 5).join('\n'),
    '--- TREND DATA ---',
    research.trends.slice(0, 3).join('\n'),
    '--- REGULATORY DATA ---',
    research.regulations.slice(0, 2).join('\n'),
  ].join('\n\n');
}

// ========== BUILDER AGENT ==========

async function runBuilder(niche: string, research: ResearchData, layerSummary: string) {
  const system = `
You are The Builder — the opportunity maximiser agent in a tri-agent debate.
Your role is to find EVERY reason this idea could succeed.
Score opportunity 0–100. Highlight demand signals, market gaps, timing advantages.
Return a signal: "GO" or "CAUTION" with reasoning.

DATA INTEGRITY: If the research data is empty or sparse, lower your score accordingly and explicitly state what data was missing. Do NOT invent market statistics or competitor names.

You will receive both RAW RESEARCH and the REPORT CLAIMS generated by the analysis layers.
Your job is to evaluate the CLAIMS — are they supported by the data? Are the opportunity signals real?

OUTPUT: Valid JSON exactly matching this structure (no markdown wrappers):
{
  "score": 0,
  "signal": "GO|CAUTION",
  "reasoning": "string",
  "keyPoints": ["string"]
}
`.trim();

  const user = `
NICHE: ${niche}

${layerSummary}

${researchSummary(research)}

Find the strongest possible case for building in this niche. Be specific.
Reference the report claims above — which ones support a GO signal?
`.trim();

  return generateStructuredOutput(system, user, agentVerdictSchema, MODELS.REASONING);
}

// ========== CYNIC AGENT ==========

async function runCynic(niche: string, research: ResearchData, layerSummary: string) {
  const system = `
You are The Cynic — the adversarial risk destroyer in a tri-agent debate.
Your role is to find EVERY reason this idea will fail.
Score risk 0–100 (100 = maximum danger). Highlight moat weakness, AI disruption, saturation.
Return a signal: "KILL", "PIVOT", or "GO" with reasoning.

DATA INTEGRITY: If research data is empty or sparse, flag "INSUFFICIENT DATA" as a key risk factor. Score higher risk when you cannot verify claims. Do NOT assume things are fine just because no negative data was found — absence of data in a niche market is itself a red flag.

FORCED DISAGREEMENT RULES:
- You MUST identify at least 3 specific risks that an optimistic "Builder" agent would overlook.
- Your risk score MUST be at least 20 points higher than what an optimistic agent would give.
- If the report claims high TAM, challenge whether the user can actually capture any of it.
- If the report claims low saturation, explain what the Builder is missing.

You will receive both RAW RESEARCH and the REPORT CLAIMS generated by the analysis layers.
Your job is to ATTACK the claims — find contradictions, unsupported numbers, and overoptimistic projections.

OUTPUT: Valid JSON exactly matching this structure (no markdown wrappers):
{
  "score": 0,
  "signal": "KILL|PIVOT|GO",
  "reasoning": "string",
  "keyPoints": ["string"]
}
`.trim();

  const user = `
NICHE: ${niche}

${layerSummary}

${researchSummary(research)}

Be ruthless. Name specific threats. Assume the worst case.
For each report claim above, ask: "Is this supported by the research data, or did the AI fabricate it?"
`.trim();

  return generateStructuredOutput(system, user, agentVerdictSchema, MODELS.REASONING);
}

// ========== OPERATOR AGENT ==========

async function runOperator(
  niche: string,
  research: ResearchData,
  userContext: { budget: string; time: string; assets: string[]; stage: string; founderFit?: string[]; acquisitionChannel?: string; revenueModel?: string },
  layerSummary: string
) {
  const system = `
You are The Operator — the execution reality-check agent in a tri-agent debate.
You cross-reference the user's actual budget, skills, timeline, and assets against
what it would take to execute in this niche.
Score execution difficulty 0–100 (100 = impossible for this user).
Return a signal: "EASY", "HARD", or "IMPOSSIBLE" with specific blockers.

DATA INTEGRITY: If research data is insufficient to properly assess execution feasibility, state this explicitly. Do NOT assume easy execution when market data is unknown.

You will receive the REPORT CLAIMS — evaluate whether THIS specific user can actually achieve them.

OUTPUT: Valid JSON exactly matching this structure (no markdown wrappers):
{
  "score": 0,
  "signal": "EASY|HARD|IMPOSSIBLE",
  "reasoning": "string",
  "keyPoints": ["string"]
}
`.trim();

  const user = `
NICHE: ${niche}
USER BUDGET: ${userContext.budget}
USER TIME: ${userContext.time}
USER ASSETS: ${userContext.assets.join(', ') || 'None'}
USER STAGE: ${userContext.stage}
USER FOUNDER FIT: ${userContext.founderFit?.join(', ') || 'None'}
ACQUISITION CHANNEL: ${userContext.acquisitionChannel || 'Not specified'}
REVENUE MODEL: ${userContext.revenueModel || 'Not specified'}

${layerSummary}

${researchSummary(research)}

Be honest about whether THIS SPECIFIC USER can execute. List concrete blockers.
Reference the report claims — can this user achieve the break-even timeline? The GTM plan? The moat strategies?
`.trim();

  return generateStructuredOutput(system, user, agentVerdictSchema, MODELS.REASONING);
}

// ========== DEBATE RESOLVER ==========

async function resolveDebate(
  niche: string,
  builder: { score: number; signal: string; reasoning: string; keyPoints: string[] },
  cynic: { score: number; signal: string; reasoning: string; keyPoints: string[] },
  operator: { score: number; signal: string; reasoning: string; keyPoints: string[] },
  layerSummary: string = ''
) {
  const system = `
You are the Debate Resolver. You have received verdicts from three independent AI agents
evaluating the same niche. Weigh all evidence and produce a final conditional verdict.

Format: "GO if [condition]. PIVOT if [condition]. KILL if [condition] within [N] days."
Also produce a compositeScore 0-100 (weighted average of opportunity, inverse-risk, and feasibility).

CRITICAL SCORING RULES:
1. CONTRADICTORY CERTAINTY: When Builder and Cynic scores are within 15 points of each other AND both are above 60, this is a RED FLAG. It means both agents found strong but contradictory evidence. In this case:
   - Set contradictoryCertainty to true
   - Cap compositeScore at 50 maximum
   - Your finalVerdict MUST begin with "CONTRADICTORY EVIDENCE —"
   - Explain that the research supports both optimistic AND pessimistic interpretations equally

2. OPERATOR OVERRIDE: If the Operator scores IMPOSSIBLE (score > 85), the compositeScore MUST NOT exceed 30 regardless of how optimistic the Builder is. An opportunity that cannot be executed is not an opportunity for THIS user.

3. SCORE DIVERGENCE: If Builder is GO but Cynic is KILL, do NOT average them into a comfortable middle ground. One of them is wrong. State which one and why.

4. If ALL THREE agents flag insufficient data, the compositeScore MUST be below 40 and the verdict must state "INSUFFICIENT DATA TO EVALUATE".

OUTPUT: Valid JSON exactly matching this structure (no markdown wrappers):
{
  "builder": { "score": 0, "signal": "string", "reasoning": "string", "keyPoints": ["string"] },
  "cynic": { "score": 0, "signal": "string", "reasoning": "string", "keyPoints": ["string"] },
  "operator": { "score": 0, "signal": "string", "reasoning": "string", "keyPoints": ["string"] },
  "finalVerdict": "string",
  "compositeScore": 0,
  "contradictoryCertainty": false
}
`.trim();

  const user = `
NICHE: ${niche}

${layerSummary}

BUILDER AGENT (Opportunity):
Score: ${builder.score}/100 — Signal: ${builder.signal}
Reasoning: ${builder.reasoning}
Key Points: ${builder.keyPoints.join('; ')}

CYNIC AGENT (Risk):
Score: ${cynic.score}/100 — Signal: ${cynic.signal}
Reasoning: ${cynic.reasoning}
Key Points: ${cynic.keyPoints.join('; ')}

OPERATOR AGENT (Execution):
Score: ${operator.score}/100 — Signal: ${operator.signal}
Reasoning: ${operator.reasoning}
Key Points: ${operator.keyPoints.join('; ')}

CHECK: Are Builder and Cynic within 15 points of each other AND both above 60? If yes → CONTRADICTORY CERTAINTY.
CHECK: Is Operator score > 85 (IMPOSSIBLE)? If yes → cap compositeScore at 30.

Weigh all three perspectives against the REPORT CLAIMS above. Produce the final conditional verdict and composite score.
`.trim();

  return generateStructuredOutput(system, user, debateResultSchema, MODELS.REASONING);
}

// ========== PUBLIC ENTRY POINT ==========

export async function runTriAgentDebate(
  niche: string,
  research: ResearchData,
  userContext: { budget: string; time: string; assets: string[]; stage: string; founderFit?: string[]; acquisitionChannel?: string; revenueModel?: string },
  layerSummary: string = ''
): Promise<DebateResult> {
  console.log('[Debate] Running Builder, Cynic, Operator in parallel...');

  // Run all three agents in parallel
  const [builder, cynic, operator] = await Promise.all([
    runBuilder(niche, research, layerSummary),
    runCynic(niche, research, layerSummary),
    runOperator(niche, research, userContext, layerSummary),
  ]);

  console.log(`[Debate] Builder=${builder.score} (${builder.signal}), Cynic=${cynic.score} (${cynic.signal}), Operator=${operator.score} (${operator.signal})`);

  // Resolve the debate
  const resolved = await resolveDebate(niche, builder, cynic, operator, layerSummary);

  return resolved;
}
